apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  # namespace: kub-wordpress
data:
  DB_NAME: wpdb
  DB_USER: wpuser
  DB_HOST: mysql-master-service
  SLAVE_HOST: mysql-slave-service
  MEMCACHED_HOST: memcached-service