apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-replica-master
  labels:
    app: mysql-master
spec:
  replicas: 1
  selector:
    app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
        - name: master
          image: mysql-master:0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: MYSQLROOTPASSWORD
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: DB_USER
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: MYSQLPASSWORD